# Generated by Django 4.1.7 on 2026-01-15 19:40

import bson.objectid
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('suggested_for', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'workouts',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='octofit_tracker.team')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='octofit_tracker.user')),
            ],
            options={
                'db_table': 'leaderboard',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='octofit_tracker.user')),
            ],
            options={
                'db_table': 'activities',
            },
        ),
    ]
